In [107]:
import pandas as pd
import numpy as np

In [108]:
x1=np.random.randint(low=1,high=20,size=(50,))

In [109]:
x2=np.random.randint(low=1,high=20,size=(50,))

In [110]:
y=3+2*x1-4*x2+np.random.random((50,))

In [111]:
y

array([-56.62078107,  11.47561942, -34.76328044, -18.02966667,
       -50.29541651, -34.38672569, -58.15853256, -16.1335088 ,
       -20.55533672, -34.02475462,  27.624015  , -32.46974118,
        17.77880789, -22.52315492,  -6.20018246, -22.44311158,
       -30.07128507, -28.64684959,   1.40456052, -14.97875703,
       -28.83679538,  33.39971669, -50.72180639, -36.72091687,
       -28.64190784, -24.02860057, -36.30778893,  13.15175548,
       -46.20961576, -54.93105796, -12.405419  , -42.41468058,
       -16.77755937,   3.0918019 , -38.83815717, -34.89596544,
         3.6110765 , -12.09992039, -22.47538156, -48.09018094,
         1.37791594,  -0.34363538, -26.09469504,  -4.52835127,
        -6.88769606,  -4.21145389,   7.94974324,  -6.31757218,
       -44.44803155, -16.30587923])

In [112]:
x1

array([ 2, 18, 13,  7,  5, 11,  7,  6, 18, 17, 18,  6,  9, 13, 17,  3,  5,
       18,  7, 15,  4, 17, 11,  6, 12, 16, 18, 11,  7,  9,  4,  3,  6,  4,
        9, 17, 14,  8, 11,  6,  5, 12,  9, 18,  5,  4,  6, 17,  4, 18])

In [113]:
x2

array([16,  7, 16,  9, 16, 15, 19,  8, 15, 18,  3, 12,  1, 13, 11,  8, 11,
       17,  4, 12, 10,  1, 19, 13, 14, 15, 19,  3, 16, 19,  6, 13,  8,  2,
       15, 18,  7,  8, 12, 16,  3,  7, 12, 11,  5,  4,  2, 11, 14, 14])

In [114]:
x=pd.DataFrame({'intercept':np.ones_like(x1),'x1':x1,'x2':x2})


In [115]:
x

intercept  x1  x2
0           1   2  16
1           1  18   7
2           1  13  16
3           1   7   9
4           1   5  16
5           1  11  15
6           1   7  19
7           1   6   8
8           1  18  15
9           1  17  18
10          1  18   3
11          1   6  12
12          1   9   1
13          1  13  13
14          1  17  11
15          1   3   8
16          1   5  11
17          1  18  17
18          1   7   4
19          1  15  12
20          1   4  10
21          1  17   1
22          1  11  19
23          1   6  13
24          1  12  14
25          1  16  15
26          1  18  19
27          1  11   3
28          1   7  16
29          1   9  19
30          1   4   6
31          1   3  13
32          1   6   8
33          1   4   2
34          1   9  15
35          1  17  18
36          1  14   7
37          1   8   8
38          1  11  12
39          1   6  16
40          1   5   3
41          1  12   7
42          1   9  12
43          1  18  11
44          1   5   5
45          1   4   4
46          1   6   2
47          1  17  11
48          1   4  14
49          1  18  14

In [116]:
w=np.zeros(x.shape[1])

In [117]:
w

array([0., 0., 0.])

In [118]:
def myprediction(features,weights):
    
    predictions=np.dot(features,weights)
    return(predictions)

In [119]:
myprediction(x,w)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [120]:
def myerror(target,features,weights):
    error=target-myprediction(features,weights)
    return(error)

In [121]:
def mycost(target,features,weights):
    error=myerror(target,features,weights)
    cost=np.dot(error.T,error)
    return(cost)

In [122]:
mycost(y,x,w)

43910.80823996248

In [123]:
def gradient(target,features,weights):
    error=myerror(target,features,weights)
    gradient = - np.dot(features.T,error)
    
    return(gradient)

In [124]:
gradient(y,x,w)

array([ 1002.96914106,  8517.35696847, 16123.69629748])

In [125]:
def my_lr(target,features,learning_rate):
    
    weights=np.zeros(features.shape[1])
    
    for i in np.arange(100000):
        
        weights -= weights - learning_rate*gradient(target,features,weights)
        weights[0] -= 10*learning_rate*gradient(target,features,weights)[0]
        
        if i%1000==0:
            print(mycost(target,features,weights),weights)
    return(weights)

In [126]:
my_lr(y,x,0.000001)

44561.24182736708 [-0.00915868  0.00851736  0.0161237 ]
44569.230185052926 [-0.00914749  0.008664    0.01629021]
44569.230185052926 [-0.00914749  0.008664    0.01629021]
44569.230185052926 [-0.00914749  0.008664    0.01629021]
44569.230185052926 [-0.00914749  0.008664    0.01629021]
44569.230185052926 [-0.00914749  0.008664    0.01629021]
44569.230185052926 [-0.00914749  0.008664    0.01629021]
44569.230185052926 [-0.00914749  0.008664    0.01629021]
44569.230185052926 [-0.00914749  0.008664    0.01629021]
44569.230185052926 [-0.00914749  0.008664    0.01629021]
44569.230185052926 [-0.00914749  0.008664    0.01629021]
44569.230185052926 [-0.00914749  0.008664    0.01629021]
44569.230185052926 [-0.00914749  0.008664    0.01629021]
44569.230185052926 [-0.00914749  0.008664    0.01629021]
44569.230185052926 [-0.00914749  0.008664    0.01629021]
44569.230185052926 [-0.00914749  0.008664    0.01629021]
44569.230185052926 [-0.00914749  0.008664    0.01629021]
44569.230185052926 [-0.00914749 

array([-0.00914749,  0.008664  ,  0.01629021])

In [127]:
from sklearn.linear_model import LinearRegression

In [128]:
lr=LinearRegression()

In [129]:
lr.fit(x.iloc[:,1:],y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [130]:
lr.coef_

array([ 1.99930714, -3.99983072])

In [131]:
lr.intercept_

3.545773641680544